<fieldset id="payment_form_stripe_payments_bank_transfers" class="stripe-payments standard-form admin__fieldset" style="display:none;">
  <div class="fieldset indent">
    <div class="control payment-method-note">
      <?= __('The customer will receive an invoice by email with bank transfer instructions.'); //phpcs:ignore ?>
    </div>

    <br>

    <h4><?= __('Payment due'); //phpcs:ignore ?></h4>
      <div class="admin__control-addon days-due">
          <input class="admin__control-text" type="text" name="payment[days_due]" id="invoice_days_due" maxlength="3" value="<?= $block->getDaysDue(); //phpcs:ignore ?>">
          <label class="admin__addon-suffix" for="invoice_days_due"><?= __('days'); //phpcs:ignore ?></label>
      </div>
      <span class="desc"><?= __('after the invoice has been sent.'); //phpcs:ignore ?></span>
  </div>
</fieldset>
